import { Teacher, ExamSession } from './types';

export const INITIAL_TEACHERS: Teacher[] = [
  { id: 'AMOP', firstName: 'Amoré', lastName: 'Pienaar', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'ARAR', firstName: 'Arabella', lastName: 'Rakhoabe', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'AYAM', firstName: 'Ayanda', lastName: 'Mngadi', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'BORC', firstName: 'Bornwise', lastName: 'Chauke', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'CHAM', firstName: 'Chare', lastName: 'Mouton', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'DINL', firstName: 'Dinovian', lastName: 'Lezar', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'EZRN', firstName: 'Ezra', lastName: 'Nyathi', roles: ['TEACHER', 'OPERATIONAL_MANAGER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'FRAN', firstName: 'Franz', lastName: 'Nortje', roles: ['WEBMASTER', 'ADMIN', 'TEACHER', 'OPERATIONAL_MANAGER'], activeRole: 'WEBMASTER', totalHours: 0, email: 'nortje.curro@gmail.com', canInvigilate: true, invigilationPreference: 'MARATHON' },
  { id: 'FUZM', firstName: 'Fuzile', lastName: 'Mbenyeza', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'GRAK', firstName: 'Grace', lastName: 'Korb', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'JACB', firstName: 'Jaco', lastName: 'Blom', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'JESL', firstName: 'Jessica', lastName: 'Lubbe', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'LENF', firstName: 'Lente', lastName: 'Ferreira', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'LIAR', firstName: 'Liam', lastName: 'Riley', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'LOGF', firstName: 'Logan', lastName: 'Fourie', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'MARS', firstName: 'Martin-Caleb', lastName: 'Sehlapelo', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'MERM', firstName: 'Mercy', lastName: 'Mvukwe', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'MERV', firstName: 'Merike', lastName: 'Van Dyk', roles: ['ADMIN', 'TEACHER', 'OPERATIONAL_MANAGER'], activeRole: 'ADMIN', totalHours: 0, canInvigilate: false, invigilationPreference: 'MARATHON' },
  { id: 'MICM', firstName: 'Michael President', lastName: 'Makowa', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'MINM', firstName: 'Minenhle', lastName: 'Mchunu', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'NOMR', firstName: 'Nomaswati', lastName: 'Rahlao', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'NTAD', firstName: 'Ntandenhle', lastName: 'Dlamini', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'NTHD', firstName: 'Nthabiseng', lastName: 'Diaman', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'ORIM', firstName: 'Oritonda Pinkie', lastName: 'Mafhungo', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'PATM', firstName: 'Patrick', lastName: 'Mkhwanazi', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'PLAL', firstName: 'Placid', lastName: 'Letswalo', roles: ['TEACHER', 'OPERATIONAL_MANAGER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'SEIM', firstName: 'Seipati', lastName: 'Mathabe', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'SHEH', firstName: 'Shelton', lastName: 'Hu', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'SOPM', firstName: 'Sophie', lastName: 'Manzie', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'SUPM', firstName: 'Suprise', lastName: 'Madlala', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'THAK', firstName: 'Thandolwethu', lastName: 'Kunene', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'THEG', firstName: 'Theana', lastName: 'Govender', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'WENV', firstName: 'Wendy-ann Gene', lastName: 'Van Der Westhuizen', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
  { id: 'ZAMJ', firstName: 'Zamani', lastName: 'Jiyani', roles: ['TEACHER'], activeRole: 'TEACHER', totalHours: 0, invigilationPreference: 'SCATTERED' },
];

export const MOCK_SESSIONS: ExamSession[] = [
  {
    id: 's1',
    date: '2026-04-17',
    subject: 'Life Sciences P1',
    paper: 'Grade 12',
    grade: 12,
    location: 'Hall A',
    startTime: '07:50',
    durationMinutes: 180,
    status: 'IN_PROGRESS',
  },
  {
    id: 's2',
    date: '2026-04-17',
    subject: 'Mathematics P1',
    paper: 'Grade 10',
    grade: 10,
    location: 'Room 12',
    startTime: '08:40',
    durationMinutes: 120,
    status: 'UPCOMING',
  },
  {
    id: 's3',
    date: '2026-04-17',
    subject: 'Business Studies',
    paper: 'Grade 11',
    grade: 11,
    location: 'Lab 3',
    startTime: '09:30',
    durationMinutes: 150,
    status: 'UPCOMING',
  },
];
